version: "3"
tasks:
  dev:
    desc: "Start the Quartz development server"
    cmds:
      - npx quartz build --serve
  clean:
    desc: "Remove generated public files"
    cmds:
      - rm -rf public
  publish:
    desc: "Commit and push changes"
    cmds:
      - git add .
      - git commit -m "new post"
      - git push
  sync:
    desc: "Sync blog content from Obsidian"
    vars:
      VAULT_PATH:
        sh: if uname -s | grep -i darwin > /dev/null; then echo "~/Obsidian/wiki/03-Blog/"; else echo "/mnt/c/Users/migue/Documents/wiki/03-Blog"; fi
    cmds:
      - cmd: rsync -r {{.VAULT_PATH}} content
